version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuração personalizada
    depends_on:
      - frontend
      - backend
    networks:
      - front_network
    restart: always

  frontend:
    image: dogogh1/frontend-blogpost:latest
    container_name: frontend
#sem porta, o nginx conecta pela rede 
    networks:
      - front_network

  backend:
    image: dogogh1/blog-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blogdb
    depends_on:
      - postgres
    networks:
      - front_network
      - banco_network

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog_pg_data:/bitnami/postgresql
    networks:
      - banco_network

volumes:
  blog_pg_data:

networks:
  banco_network:
    driver: bridge
  front_network:
    driver: bridge