filebeat.inputs:
  - type: log
    paths:
      - '/var/log/*.log'  # Captura todos os arquivos .log em /var/log
      - '/var/log/**/*.log'  # Captura recursivamente todos os arquivos .log dentro de subdiretórios
    fields:
      log_type: system  # Você pode ajustar este campo se necessário
    multiline.pattern: '^\s'  # Combine múltiplas linhas de logs se necessário
    multiline.negate: true
    multiline.match: after

setup.template.name: "docker-back-logs"
setup.template.pattern: "docker-back-logs-*"

# Saída para Elasticsearch
output.elasticsearch:
  hosts: ['http://elasticsearch:9200']  # Certifique-se de que o Elasticsearch está acessível a partir do contêiner
  index: "docker-logs-%{+yyyy.MM.dd}"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat  # O diretório onde os logs do Filebeat serão armazenados
  name: filebeat
  keepfiles: 7
  permissions: 0644
