filebeat.inputs:
  - type: docker
    containers.ids: '*'
    paths:
      - '/var/lib/docker/containers/*/*.log'
    fields:
      log_type: container
    multiline.pattern: '^\s'
    multiline.negate: true
    multiline.match: after

setup.template.name: "docker-logs"
setup.template.pattern: "docker-logs-*"

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  index: "docker-logs-%{+yyyy.MM.dd}"



filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    container_name: filebeat
    restart: always
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml  
      - /var/log:/var/log  
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - front_network
      - banco_network