services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - front_network
    restart: always

  frontend:
    image: dogogh1/frontend-blogpost:latest
    container_name: frontend
    expose:
      - "3000"
    environment:
      - VITE_API_URL=/api
      - VITE_ENCRYPTION_KEY=asdasdasdsadasdsadad
    networks:
      - front_network

  backend:
    image: dogogh1/blog-backend:latest
    container_name: backend
    expose:
      - "3000"
    volumes:
      - ../uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blogdb
    depends_on:
      - postgres
    networks:
      - front_network
      - banco_network

  postgres:
    image: postgres:latest  # Nome correto da imagem oficial
    container_name: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    volumes:
      - blog_pg_data:/bitnami/postgresql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - banco_network

  elasticsearch:
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - front_network
    restart: always

  kibana:
    image: bitnami/kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - front_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.0
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ../filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - front_network
    restart: always

volumes:
   blog_pg_data:

networks:
  banco_network:
    driver: bridge
  front_network:
    driver: bridge