name: Flask CI Workflow

on:
  push:
    branches:
      - pipe
  pull_request:
    branches:
      - pipe

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: user testes
      run: |
        . venv/bin/activate
        pytest tests/user_test.py --maxfail=1 --disable-warnings -q
    - name: comment testes
      run: |
        . venv/bin/activate
        pytest tests/comment_test.py --maxfail=1 --disable-warnings -q

   
   
