name: Flask CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: blogdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set DATABASE_URL environment variable
      run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/blogdb" >> $GITHUB_ENV

    - name: Wait for PostgreSQL to be ready
      run: |
        sudo apt-get install -y netcat
        while ! nc -z localhost 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run database migrations
      run: |
        . venv/bin/activate
        flask db upgrade  # Aplica as migrações para criar as tabelas

    - name: Run user tests
      run: |
        . venv/bin/activate
        pytest tests/user_test.py --maxfail=1 --disable-warnings -q

    - name: Run comment tests
      run: |
        . venv/bin/activate
        pytest tests/comment_test.py --maxfail=1 --disable-warnings -q
