name: Flask CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Run user tests
    #  run: |
     #   . venv/bin/activate
     #   pytest tests/user_test.py --maxfail=1 --disable-warnings -q
    
   # - name: Run post tests 
    #  run: |
    #    . venv/bin/activate
     #   pytest tests/comment_test.py --maxfail=1 --disable-warnings -q

  build-and-push:
    needs: test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t dogogh1/blog-backend:latest .

      - name: Push Docker image
        run: docker push dogogh1/blog-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    
    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH into VPN Server using password
      run: |
        sshpass -p 'vmvpn' ssh -o StrictHostKeyChecking=no vmvpn@34.123.48.112 << 'EOF'
        # Comandos para o primeiro SSH no servidor VPN
      
          sshpass -p 'admin' ssh -o StrictHostKeyChecking=no backend@10.0.1.4 << 'INNER_EOF'
            # Navegar até o diretório onde o docker-compose.yml está localizado
            cd /home/backend
            
            # Parar e remover os containers com Docker Compose
            docker compose down
            
            # Remover as imagens Docker, se necessário
            docker system prune -af
            
            # Subir novamente os containers com Docker Compose
            docker compose up -d
          INNER_EOF
        EOF




        
